USE [master]
GO

/****** Object:  Database [Berf]    Script Date: 27/06/2014 16:39:15 ******/
DROP DATABASE [Berf]
GO

/****** Object:  Database [Berf]    Script Date: 27/06/2014 16:39:15 ******/
CREATE DATABASE [Berf]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Berf', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER2012\MSSQL\DATA\Berf.mdf' , SIZE = 94272KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Berf_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER2012\MSSQL\DATA\Berf_log.ldf' , SIZE = 1856KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Berf] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Berf].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Berf] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Berf] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Berf] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Berf] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Berf] SET ARITHABORT OFF 
GO

ALTER DATABASE [Berf] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Berf] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Berf] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Berf] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Berf] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Berf] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Berf] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Berf] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Berf] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Berf] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Berf] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Berf] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Berf] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Berf] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Berf] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Berf] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Berf] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Berf] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Berf] SET RECOVERY FULL 
GO

ALTER DATABASE [Berf] SET  MULTI_USER 
GO

ALTER DATABASE [Berf] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Berf] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Berf] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Berf] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Berf] SET  READ_WRITE 
GO



